/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedNcRouteImport } from './routes/_authenticated/nc'
import { Route as AuthenticatedCapaRouteImport } from './routes/_authenticated/capa'
import { Route as AuthenticatedAmdecRouteImport } from './routes/_authenticated/amdec'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNcRoute = AuthenticatedNcRouteImport.update({
  id: '/nc',
  path: '/nc',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCapaRoute = AuthenticatedCapaRouteImport.update({
  id: '/capa',
  path: '/capa',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAmdecRoute = AuthenticatedAmdecRouteImport.update({
  id: '/amdec',
  path: '/amdec',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/amdec': typeof AuthenticatedAmdecRoute
  '/capa': typeof AuthenticatedCapaRoute
  '/nc': typeof AuthenticatedNcRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/amdec': typeof AuthenticatedAmdecRoute
  '/capa': typeof AuthenticatedCapaRoute
  '/nc': typeof AuthenticatedNcRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/amdec': typeof AuthenticatedAmdecRoute
  '/_authenticated/capa': typeof AuthenticatedCapaRoute
  '/_authenticated/nc': typeof AuthenticatedNcRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/amdec' | '/capa' | '/nc'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/amdec' | '/capa' | '/nc' | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/amdec'
    | '/_authenticated/capa'
    | '/_authenticated/nc'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nc': {
      id: '/_authenticated/nc'
      path: '/nc'
      fullPath: '/nc'
      preLoaderRoute: typeof AuthenticatedNcRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/capa': {
      id: '/_authenticated/capa'
      path: '/capa'
      fullPath: '/capa'
      preLoaderRoute: typeof AuthenticatedCapaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/amdec': {
      id: '/_authenticated/amdec'
      path: '/amdec'
      fullPath: '/amdec'
      preLoaderRoute: typeof AuthenticatedAmdecRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAmdecRoute: typeof AuthenticatedAmdecRoute
  AuthenticatedCapaRoute: typeof AuthenticatedCapaRoute
  AuthenticatedNcRoute: typeof AuthenticatedNcRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAmdecRoute: AuthenticatedAmdecRoute,
  AuthenticatedCapaRoute: AuthenticatedCapaRoute,
  AuthenticatedNcRoute: AuthenticatedNcRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
